// Generated by CoffeeScript 1.7.1
(function() {
  var Robot, robot;

  Robot = require('../controller/robot');

  console.log(Robot);

  robot = new Robot({
    name: "Robot@again.cc"
  });

}).call(this);

//# sourceMappingURL=robot.map
