// Generated by CoffeeScript 1.7.1
(function() {
  var Diary, Q, Robot, ejs, mailTemplate, moment, path, robot, setting, start;

  Robot = require('../controller/robot');

  setting = require("../settings");

  path = require('path');

  Diary = require('../models/database.js').Diary;

  Q = require('q');

  moment = require('moment');

  moment.lang('zh-cn');

  ejs = require('ejs');

  mailTemplate = path.resolve(__dirname, "../views/templates/mail.html");

  robot = new Robot({
    name: "Wall-E"
  });

  start = function() {

    /*
    Daily Mail
     */
    var dailyMail, newJob;
    dailyMail = function() {
      var dailyMailDefer, diaryDefer, sendEmail;
      dailyMailDefer = Q.defer();
      diaryDefer = Q.defer();
      sendEmail = function(content) {
        ejs.renderFile(mailTemplate, content, function(err, data) {
          if (err) {
            dailyMailDefer.reject(err);
            return false;
          }
          console.log("Sending Daily Mail.....");
          return robot.mail({
            from: setting.mailfrom,
            to: setting.mailto,
            subject: "[Daily Mail] How is your day going? [" + (moment().format('ll')) + "]",
            html: data
          }).then(function(data) {
            console.log("Daily Mail Sent.");
            return dailyMailDefer.resolve(data);
          }, function(error) {
            return dailyMailDefer.reject(error);
          });
        });
        return dailyMailDefer.promise;
      };
      Diary.random(function(err, result) {
        if (err) {
          diaryDefer.reject(err);
          return false;
        }
        result = result || {
          content: "There is nothing here."
        };
        result.now = moment(new Date()).format('ll');
        result.time = result.time ? "" + (moment(new Date(result.time)).fromNow()) + "  [" + (moment(new Date(result.time)).format("LLLL")) + "]" : "[No Memory]";
        return sendEmail(result).then(function(data) {
          return diaryDefer.resolve(data);
        }, function(err) {
          return diaryDefer.reject(err);
        });
      });
      return diaryDefer.promise;
    };
    console.log("Adding to Schedule......");
    newJob = robot.schedule({
      job: dailyMail,
      hour: 0,
      minute: 0
    });
    return newJob.runOnDate(new Date());
  };

  exports.start = start;

}).call(this);

//# sourceMappingURL=robot.map
