// Generated by CoffeeScript 1.7.1
(function() {
  var AWS, Q, Robot, S3, Twit, mailer, nodemailer, request, rssParser, schedule, setting, twitter;

  setting = require('../../settings');

  require('colors');

  nodemailer = require("nodemailer");

  Q = require("q");

  schedule = require('node-schedule');

  request = require('superagent');

  Twit = require('twit');

  rssParser = require("rssparser");

  AWS = require('aws-sdk');

  AWS.config.loadFromPath('./config.json');

  AWS.config.apiVersion = {
    s3: '2006-03-01'
  };

  S3 = new AWS.S3();

  twitter = new Twit({
    consumer_key: setting.twitter.consumerKey,
    consumer_secret: setting.twitter.consumerSecret,
    access_token: setting.twitter.accessToken,
    access_token_secret: setting.twitter.accessTokenSecret
  });

  mailer = nodemailer.createTransport('SMTP', {
    service: 'Mailgun',
    auth: {
      user: setting.mailgun.user,
      pass: setting.mailgun.pass
    }
  });

  Robot = (function() {
    function Robot(config) {
      var jobs, result;
      this.name = config.name || "Robot A";
      this.gender = config.gender || "Boy";
      this.birthday = new Date();
      this.age = config.gender || new Date() - this.birthday;
      this.bio = "Robot Can Sleep, too.";
      this.jobs = [];
      console.log("System initializing.......");
      console.log("New Robot Generated with name: " + this.name);
      console.log("" + this.name + " is starting......");
      console.log("Please Wait....");
      console.log("Checking for healthy......");
      result = this.checkHealth();
      if (result.error) {
        console.log("" + result.error);
        return false;
      }
      console.log("Health Check pass.".green);
      console.log("Robot " + this.name + " is online now.");
      jobs = this.checkJobs();
      if (jobs.length) {
        console.log("We got last jobs. ");
      }
    }

    Robot.prototype.mail = function(options) {
      var mailDiffer;
      console.log(options);
      console.log(this);
      options.subject = ("[" + this.name + "]") + options.subject;
      mailDiffer = Q.nfcall(mailer.sendMail, options);
      mailDiffer.then(function() {
        return console.log(arguments);
      }, function() {
        return console.log(arguments);
      });
      return mailDiffer;
    };

    Robot.prototype.checkHealth = function() {
      return {};
    };

    Robot.prototype.checkJobs = function() {
      return this.jobs;
    };

    Robot.prototype.handler = function(err) {
      return console.log(new Error(err));
    };

    Robot.prototype.addSchedule = function(jobfunc, option) {
      var loopJob, loopTime;
      if (option.loop) {
        loopTime = new schedule.RecurrenceRule();
        loopTime.hour = option.hour;
        loopJob = schedule.scheduleJob(loopTime, jobfunc);
        this.jobs.push({
          job: loopJob,
          loop: loopTime
        });
        return console.log('Added To LoopJobs');
      }
    };

    Robot.prototype.web = function(options) {
      var def, deferred, method;
      def = null;
      method = options.method.toLowerCase();
      if (method === 'get' || method === 'put' || method === 'del' || method === 'post' || method === 'head') {
        def = request[method](options.url);
      }
      if (options.data) {
        def = def.send(data);
      }
      if (options.header) {
        def = def.set(options.header);
      }
      deferred = Q.defer();
      def.end(function(res) {
        if (res.error) {
          return deferred.reject(res);
        } else {
          return deferred.resolve(res);
        }
      });
      def.on('error', function(error) {
        return deferred.reject(error);
      });
      return deferred.promise;
    };

    Robot.prototype.twitter = function(options) {
      var defer;
      defer = Q.defer();
      twitter[options.method](options.action, options.data, function(err, result) {
        if (err) {
          return defer.reject(err);
        } else {
          return defer.resolve(result);
        }
      });
      return defer.promise;
    };

    Robot.prototype.storage = function(options) {
      var option, s3Defer;
      option = {
        Bucket: setting.S3Bucket,
        key: option.name || path.resolve(options.path).split('/').pop(),
        ACL: options["private"] && options["private"] !== 'public' ? "private" : "public-read"
      };
      s3Defer = Q.defer();
      fs.readFile(options.path, (function(_this) {
        return function(err, file) {
          if (err(_this.handler(err))) {

          } else {
            (function(file) {});
          }
          option.Body = file;
          return S3.putObject(option, function(err, data) {
            if (err) {
              return s3Defer.reject(err);
            } else {
              return s3Defer.resolve(data);
            }
          });
        };
      })(this));
      return s3Defer.promise;
    };

    Robot.prototype.rss = function(options) {
      var rssDefer;
      rssDefer = Q.defer();
      parser.parseURL(options.url, options, function(err, out) {
        if (err) {
          return rssDefer.reject(err);
        } else {
          return rssDefer.resolve(out);
        }
      });
      return rssDefer.promise;
    };

    return Robot;

  })();

}).call(this);

//# sourceMappingURL=index.map
