// Generated by CoffeeScript 1.7.1
(function() {
  var figure;

  figure = function() {
    return [
      {
        type: 'lang',
        filter: function(text) {
          var imageMarkdownRegex, pathRegex, uriRegex;
          imageMarkdownRegex = /^(?:\{<(.*?)>\})?!(?:\[([^\n\]]*)\])(?:\(([^\n\]]*)\))?$/gim;
          uriRegex = /^(?!mailto:)(?:(?:https?|ftp):\/\/)?(?:\S+(?::\S*)?@)?(?:(?:(?:[1-9]\d?|1\d\d|2[01]\d|22[0-3])(?:\.(?:1?\d{1,2}|2[0-4]\d|25[0-5])){2}(?:\.(?:[0-9]\d?|1\d\d|2[0-4]\d|25[0-4]))|(?:(?:[a-z\u00a1-\uffff0-9]+-?)*[a-z\u00a1-\uffff0-9]+)(?:\.(?:[a-z\u00a1-\uffff0-9]+-?)*[a-z\u00a1-\uffff0-9]+)*(?:\.(?:[a-z\u00a1-\uffff]{2,})))|localhost)(?::\d{2,5})?(?:\/[^\s]*)?$/i;
          pathRegex = /^(\/)?([^\/\0]+(\/)?)+$/i;
          return text.replace(imageMarkdownRegex, function(match, key, alt, src) {
            var output, result;
            if (src && (src.match(uriRegex) || src.match(pathRegex))) {
              result = '<img class="image" alt="' + alt + '" src="' + src + '"/>';
            }
            output = "<figure id=\"image_upload_" + key + "\" class=\"figure\">\n" + result + "\n<figcaption>" + alt + "</figcaption>\n</figure>";
            return output;
          });
        }
      }
    ];
  };

  module.exports = figure;

}).call(this);

//# sourceMappingURL=figure_for_showdown.map
